server.port=18081
server.tomcat.uri-encoding=utf-8
mybatis.mapperLocations=classpath:mapper/*.xml
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1/logindata?useUnicode=true&serverTimezone=GMT%2b8
spring.datasource.username=root
spring.datasource.password=LYX426815
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.max-lifetime =30000
spring.profiles.active=dev
